config/routes.rb
NewMexicoSoftwareProject::Application.routes.draw do

  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :presence => true
  validates :city, :presence => true
  has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :company
  has_and_belongs_to_many :technologies
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates :name, :presence => true

  has_and_belongs_to_many :projects
#  has_many :companies, :through => :projects
#  def companies
#    projects.collect{|p|p.company}
#  end
  def companies
    projects.map &:company
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create(params[:company])
    redirect_to @company
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
%tr{:id => "company_#{company.id}"}
  %td{:class => :name}= company.name
  %td{:class => :actions}
    %ul
      %li= link_to 'Edit', edit_company_path(company)
      %li= link_to 'Delete', company_path(company)

app/views/companies/index.html.haml
%table{:id => 'companies'}
  %thead
    %tr
      %th{:class => [:cute, :name]} Name
      %th{:class => :actions}
  %tbody
    = render @companies
%ul.actions
  %li.new-company
    Add a company

app/views/companies/new.html.haml
= form_for @company do |f|
  %p
    = f.label :name, 'Name'
    = f.text_field :name
  %p
    = f.label :name, 'City'
    = f.text_field :city
  %p= f.submit 'Create Company'

app/views/companies/show.html.haml
%h1#company_name= h @company.name

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title= t(:notes)
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield :head
  %body
    #container
      = yield